# Generated by Django 3.0.2 on 2020-04-11 08:15

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.FileField(default='', upload_to='images/employees/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('image', models.FileField(upload_to=api.models.PathAndRename('/banner'), verbose_name='Banner')),
                ('active_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeSelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AdsBundle',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.Product')),
                ('ads_bundle_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_click', models.IntegerField()),
            ],
            bases=('api.product',),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.Product')),
                ('feature_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            bases=('api.product',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.Product')),
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bedroom_total', models.IntegerField(default=1)),
                ('guest_maximum', models.IntegerField(default=1)),
                ('bathroom_total', models.IntegerField(default=1)),
                ('sqm_room', models.IntegerField(default=24)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('contact_person_name', models.CharField(default='', max_length=200)),
                ('contact_person_phone', models.CharField(default='', max_length=200)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Apartment')),
            ],
            bases=('api.product',),
        ),
        migrations.CreateModel(
            name='RoomImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=api.models.PathAndRename('/products'), verbose_name='Room')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_images', to='api.Product')),
            ],
        ),
        migrations.CreateModel(
            name='RoomDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type_selling', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.TypeSelling')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_detail', to='api.Room')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('midtrans_id', models.TextField(default='')),
                ('invoice_ref_number', models.TextField()),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('expired_date', models.DateTimeField()),
                ('payment_date', models.DateTimeField()),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField()),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.OrderStatus')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Product')),
                ('type_selling', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.TypeSelling')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id', 'midtrans_id', 'invoice_ref_number')},
            },
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click', models.IntegerField()),
                ('expired_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Product')),
            ],
        ),
        migrations.CreateModel(
            name='RoomFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.RoomDetail')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_header', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.OrderHeader')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='AdsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('midtrans_id', models.TextField(default='')),
                ('expired_date', models.DateTimeField(default=None)),
                ('payment_date', models.DateTimeField(default=None)),
                ('order_status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.OrderStatus')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.AdsBundle')),
            ],
            options={
                'unique_together': {('id', 'midtrans_id')},
            },
        ),
    ]
