# Generated by Django 3.0.2 on 2020-04-13 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200413_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimages',
            name='product',
        ),
        migrations.AddField(
            model_name='roomimages',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room_images', to='api.Room'),
        ),
    ]
