# Generated by Django 3.0.2 on 2020-04-14 12:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200413_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.FileField(upload_to=api.models.PathAndRename('images/banners/'), verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='roomimages',
            name='image',
            field=models.FileField(upload_to=api.models.PathAndRename('images/products/'), verbose_name='Room'),
        ),
    ]
