# Generated by Django 3.0.2 on 2020-01-23 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200120_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Products'),
        ),
        migrations.AlterField(
            model_name='adsorder',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.AdsBundle'),
        ),
        migrations.AlterField(
            model_name='features',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Features'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.OrderHeader'),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.OrderStatus'),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Products'),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='type_selling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.TypeSelling'),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productsdetail',
            name='type_selling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Features'),
        ),
        migrations.AlterField(
            model_name='productsdetailfeatures',
            name='features',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Features'),
        ),
        migrations.AlterField(
            model_name='productsdetailfeatures',
            name='product_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ProductsDetail'),
        ),
    ]
