# Generated by Django 3.0.2 on 2020-04-15 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200415_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click', models.IntegerField(default=0)),
                ('expired_date', models.DateTimeField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Room')),
            ],
        ),
        migrations.DeleteModel(
            name='Ads',
        ),
    ]
