# Generated by Django 3.0.2 on 2020-04-16 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200415_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderheader',
            name='type_selling',
            field=models.ForeignKey(blank=None, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.TypeSelling'),
        ),
    ]
