# Generated by Django 3.0.2 on 2020-03-22 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200206_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderheader',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productsdetail',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='orderheader',
            name='midtrans_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='productsdetail',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.Products'),
        ),
    ]
