# Generated by Django 3.0.2 on 2020-03-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200322_0619'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderheader',
            unique_together={('id', 'midtrans_id', 'invoice_ref_number')},
        ),
    ]
