# Generated by Django 3.0.2 on 2020-04-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200416_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderheader',
            name='payment_number',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orderheader',
            name='payment_type',
            field=models.TextField(null=True),
        ),
    ]
