# Generated by Django 3.0.2 on 2020-03-28 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200322_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsbundle',
            name='total_click',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='api.Products'),
        ),
    ]
