# Generated by Django 3.0.2 on 2020-04-18 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='order_header',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api.OrderHeader'),
        ),
    ]
